arch: DocParseNet
batch_size: 64
cfg: null
dataset: /users/PAS0536/amsh/Document-IE-Mengxi/doc-id-divided/0/train
datasetv: /users/PAS0536/amsh/Document-IE-Mengxi/doc-id-divided/0/valid
deep_supervision: false
early_stopping: 50
epochs: 1700
factor: 0.1
gamma: 0.6666666666666666
img_ext: .png
input_channels: 3
input_h: 1024
input_w: 1024
loss: BCEDiceLoss
lr: 0.01
mask_ext: .png
milestones: 1,2
min_lr: 1.0e-05
momentum: 0.9
name: docparsenet0
nesterov: false
num_classes: 1
num_workers: 4
optimizer: Adam
patience: 2
scheduler: CosineAnnealingLR
weight_decay: 0.0001
